# Generated by Django 5.1.4 on 2025-02-19 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_category_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_appointment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
