# Generated by Django 5.1.4 on 2025-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=20, null=True),
        ),
    ]
